apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: sc1
  annotations: 
    is-default-class: 'true'
provisioner: nfs.csi.k8s.io
mountOptions: 
  - ReadWriteMany
reclaimPolicy: Delete
#parameters:
