apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-local1
spec:
  storageClassName: ''
  capacity:
    storage: 1Gi
  volumeMode: Filesystem #Block
  accessModes:
    - ReadWriteMany #ReadWriteOnce,ReadOnlyMany,ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain #Delete,Recycle
  local:
    
