apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volserver1
provisioner: ebs.csi.aws.com #nfs.csi.k8s.io
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io2
  throughput: "125"
  iopsPerGB: "50"
  encrypted: "true"
  tagSpecification_1: "key1=value1"
  tagSpecification_2: "key2=value2"
volumeBindingMode: Immediate
