apiVersion: v1
kind: Service
metadata:
  name: app-serv1
  namespace: ts
kind:
  type: NodePort #ClusterIP, LoadBalancer
  selector:
    matchLabels:
      app_name: mithun-app
  ports:
    - targetPort: tomcp
      port: 80
      nodePort: 30000
