apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volserver1
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
parameters:
  server: 172.30.2.2
  share: /mnt/nfsvol
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
