apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ts
spec: 
  storageClassName: local-sc1-default
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
