apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdep1
  namespace: ts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template: 
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - name: tomcp
              containerPort: 8080
          volumeMounts:
            - name: local-vol-1
              mountPath: /tmp
      volumes:
        - name: local-vol-1
          local: 
            name: pers-vol-1

            
