apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ts
spec:
  volumeName: pers-vol1 #name to create volume
  accessModes:  # access modes through which app will access the volume
    - ReadWriteMany 
  resources:  # resource specs to create volume with specific details
    requests:
      storage: 1Gi 
