apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain #def: Delete
parameters:
  server: 172.30.2.2
  share: /mnt/nfsvol
mountOptions:
  - nfsvers=4.1
#volumeMode: filesystem
#accessmodes: 
#  - ReadWriteMany
