apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdep1
  namespace: ts
spec:
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: app10
  template:
    metadata:
      labels:
        app: app10
    spec:
      nodeName: node01
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp
          #livenessProbe
          #resources and limits
          #volumeMounts
