apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc1
  namespace: ts
spec:
  resources: 
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs
