---
apiVersion: v1
kind: Deployment
metadata: 
  name: webdep4
  namespace: ts
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: webapp4
  template:
    metadata:
      labels:
        app: webapp4
    spec:
      containers:
        - name: tomc4
          image: heartocean/docom:kj11
          ports:
            - name: tomcp
              containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values: 
                      - first_node
                      - node_one
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 3
              preference:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - first_node
                      - node_one
      volumes:
        - name: nfs1
          nfs:
            persistentVolumeClaim:     
...
