apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoZWFydG9jZWFuIiwicGFzc3dvcmQiOiJoZWFydG9jZWFuQGRvY2tlciIsImF1dGgiOiJhR1ZoY25SdlkyVmhianBvWldGeWRHOWpaV0Z1UUdSdlkydGxjZz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: ts
type: kubernetes.io/dockerconfigjson

