apiVersion: v1
kind: ReplicationController
metadata: 
  name: mrepliction
  namespace: ts
spec:
  replicas: 2
  selector:
    name: mavenapp
  template:
    metadata: 
      name: mavenapptemplate
      labels:
        name: mavenapp
    spec:
      containers:
      - name: mavenc
        image: heartocean/k8s:19
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: mservice
  namespace: ts
spec:
  type: ClusterIP
  selector:
    name: mavenapp
  ports:
  - port: 80
    targetPort: 8080
