apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1dep 
  namespace: ts
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: spring
  template:
    metadata:
      labels: 
        app: spring
    spec:
      containers:
        - name: app1
          image: heartocean/docom:kj11
          ports: 
            - containerPort: 8080
              name: tomp
          volumeMounts:
            - name: nfs-vol1
              mountPath: /tmp
      volumes:
        - name: nfs-vol1
          persistentVolumeClaim: 
            claimName: nfs-pvc1 
