apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-vol1
  labels:
    type: nfs
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    server: 10.0.0.39
    path: /mnt/nfs1
  mountOptions:
    - nfsvers=4.2
