---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep1
  namespace: ts
spec:
  replicas: 1 
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app_name: mithun-app
  template:
    metadata:
      labels: 
        app_name: mithun-app
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp
          env:
            - name: MONGO_DB_USERNAME
              value: muser
            - name: MONGO_DB_PASSWORD
              value: mongopass
            - name: MONGO_DB_HOSTNAME
              value: mongoc
          resources:
            requests:
              cpu:  "180m"
              memory: "15Mi"
            limits:
              cpu: "200m"
              memory: "20Mi"

        - name: mongoc
          image: mongo
          ports:
            - name: mongop
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: muser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          resources:
            requests:
              cpu:  "180m"
              memory: "15Mi"
            limits:
              cpu: "200m"
              memory: "20Mi"      
          volumeMounts:
            - name: nfs-vol1
              mountPath: /data/db

      volumes:
        - name: nfs-vol1
          persistentVolumeClaim:
            claimName: pvc1
          #hostPath:
          #  path: /home/garuda/space
          #  type: DirectoryOrCreate
...
