apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ts
spec:
  storageClassName: volserver1
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
