apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdep
  namespace: ts
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: spring
  template:
    metadata:
      labels: 
        app: spring
    spec:
      containers:
        - name: app2
          image: heartocean/docom:kj11
          ports: 
            - containerPort: 8080
              name: tomp
          volumeMounts:
            - name: hp-vol-1
              mountPath: /tmp
      volumes:
        - name: hp-vol-1
          persistentVolumeClaim: 
            claimName: pvc1
