apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ts
  labels:
    app: pod1
spec:
  containers:
    - name: tomc
      image: heartocean/docom:kj11
      ports:
        - containerPort: 8080
          name: tomport
---
apiVersion: v1
kind: Service
metadata: 
  name: s1
  namespace: ts
spec:
  type: ClusterIP
  selector:
      app: pod1
  ports: 
    - targetPort: tomport
      port: 80

