apiVersion: v1
kind: Pod
metadata:
  name: tomcat
spec:
  containers: 
  - name: mavenapp
    image: heartocean/utility:tomcat_sudo
    ports: 
    - containerPort: 8080

apiVersion: v1
kind: Service
metadata: 
  name: mavenapp_service
spec:
  selector:
  
