apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MSI6eyJ1c2VybmFtZSI6ImhlYXJ0b2NlYW4iLCJwYXNzd29yZCI6ImhlYXJ0b2NlYW5AZG9ja2VyIiwiZW1haWwiOiJjdjI3Lm9uZUBnbWFpbC5jb20iLCJhdXRoIjoiYUdWaGNuUnZZMlZoYmpwb1pXRnlkRzlqWldGdVFHUnZZMnRsY2c9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: ts
type: kubernetes.io/dockerconfigjson
