apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep3
  namespace: ts
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 4
  selector: 
    matchLabels:
      app: mavenapp2
  template:  
    metadata:
      name: pod1-template
      labels:
        app: mavenapp2
    spec:
      containers:
      - name: mavenapp2c
        image: heartocean/k8s:6
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: mav2serv
  namespace: ts
spec:
  type: NodePort
  selector:
    app: mavenapp2
  ports:
  - protocol:  TCP
    port: 80
    targetPort: 8080
    nodePort: 30003
