apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress1
spec:
  rules:
    - http:
      paths:
        - path: /
          pathType: prefix
          backend:
            service:
              name: sserv
              port:
                number: 80
