apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: sc1
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.39
  share: /mnt/nfs1
mountOptions:
  - nfsvers=4.2
reclaimPolicy: Retain
