apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "selectorLabels" . | indent 4 }}
  ports:
    - targetPort: 
      port: 80
