apiVersion: v1
kind: Namespace
metadata: 
  name: ts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dep1
  namespace: ts
spec: 
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    app: demo-app1
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          env:
            - name: MONGODB_ROOT_USERNAME
              value: mongo
            - name: MONGODB_ROOT_PASSWORD
              value: mongopass
            - name: MONGODB_ROOT_HOSTNAME
              value: mongoc
          ports: 
            - containerPort: 8080
              name: tomcp
          volumeMounts:
            - name: vol1
              mountPath: /data/db
--- 
apiVersion: v1
kind: Service
metadata:
  name: serv1
  namespace: ts
spec:
  type: NodePort
  selector:
    app: demo-app1
  ports:
    - targetPort: tomcp
      port: 80
      nodePort: 30000
