apiVersion: v1
kind: Service
metadata: 
  name: ingress-example1 
  namespace: ts
spec: 
  type: NodePort
  selector:
      app: app1 
  ports:
    - port: 80
      targetPort: 8080 
      nodePort: 30006
