apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomrs 
  namespace: ts
spec:
  selector:
    matchLabels:
      app: mavenapp
  replicas: 2
  template: #pod template
    metadata:
      name: maventemp
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavec
        image: heartocean/k8s:18
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mserv
  namespace: ts
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30002
