apiVersion: v1
kind: PersistentVolume
metadata:
  name: pers-vol1
spec:
  local: 
    path: /mnt/disk1
  capacity:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: In
            values:
              - first
