apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp1
  labels:
    handle: pv-hp1
spec:
  storageClassName: ''
  capacity:
    storage: 1Gi
  volumeMode: Filesystem #Block
  accessModes:
    - ReadWriteOnce #ReadOnlyMany, ReadWriteMany, ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain #Recycle, Delete
  hostPath:
    path: /space
    type: DirectoryOrCreate #"", Directory,FileOrCreate,File,Socket,CharDevice,BlockDevice
