apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app10
  template:
    metadata:
      labels:
        app: app10
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - first
                    - one
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp          
