apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app10ing
  namespace: ts
spec: 
  ingressClassName: nginx
  rules:
    - http:
        paths: 
          - path: /app10
            pathType: Prefix
            backend:
              service: 
                name: app10serv
                port: 
                  number: 80
                
