apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ts
spec:
  storageClassName: '' 
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: app10vol
