apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: all-pvc1
spec:
  defaultStorageClass: ''
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
