apiVersion: v1
kind: Deployment
metadata:
  name: all-app1-dep
  namespace: ts
spec:
  affinity:
    nodeAffinity:
      requiredBeforeSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key:
                operator: In
                values:
                  - first
                  - one
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: all-app1
  template:
    metadata:
      labels:
        app: all-app1
  spec:
    containers:
      - name: tomc
        image: heartocean/docom:kj11
        ports:
          - containerPort: 8080
            name: tomcp
        env:
          - name: MONGODB_ROOT_USERNAME
            value: mongouser
          - name: MONGODB_ROOT_PASSWORD
            value: mongopass
          - name: MONGODB_ROOT_HOSTNAME
            value: mongoc
        livenessProbe:
          exec:
            command:
              - curl
              - http://localhost:8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: mongoc
        image: mongo
        ports: 
          - containerPort: 27017
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopass
        livenessProbe: 
          exec:
            command:
              - touch 
              - /space2
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: all-vol1
            mountPath: /data/db
    volumes:
      - name: all-vol1
        persistentVolumeClaim:
          claimName: all-pvc1
