apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dep1
  namespace: ts
spec: 
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: demo-app1
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          env:
            - name: MONGODB_ROOT_USERNAME
              value: mongo
            - name: MONGODB_ROOT_PASSWORD
              value: mongopass
            - name: MONGODB_ROOT_HOSTNAME
              value: mongoc
          ports: 
            - containerPort: 8080
              name: tomcp
        - name: mongoc
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          volumeMounts:
            - name: vol1
              mountPath: /data/db
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvclaim1 
