apiVersion: v1
kind: Secret
metadata:
  name: svc-acc-token
  namespace: ts
  annotations: 
    kubernetes.io/service-account.name: 'sa-name'
type: kubernetes.io/service-account-token
data: # data should be given in 'base64' format
  token_key: dG9rZW5fdmFsdWUK  
