apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sset-ebs-1
  namespace: ts
spec:
  replicas: 3
  selector:
    matchLabels:
      appname: mithun-app
  template:
    metadata:
      name: mithun-app-temp1
      labels:
        appname: mithun-app
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kaniko3
          ports:
            - name: tomcp
              containerPort: 8080
          env:
            - name: MONGO_DB_USERNAME
              value: muser
            - name: MONGO_DB_PASSWORD
              value: mongopass
            - name: MONGO_DB_HOSTNAME
              value: mongoc
        - name: mongoc
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: muser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          volumeMounts:
            - name: vol1
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: vol1
      spec:
        storageClassName: storage-server-ebs
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
