apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-server-ebs
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete 
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer #Immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
  tagSpecification_1: "key1=value1"
  tagSpecification_2: "key2=value2"
