apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol1
  namespace: ts
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem 
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
