apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc1-default
  namespace: ts
  annotations:
    storage.k8s.io/is-default-class: 'true'
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
