apiVersion: v1
kind: Service
metadata:
  name: sertom
  namespace: ts
spec:
  type: LoadBalancer
  selector:
    app: mavenApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
