apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavdep
  namespace: ts
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      name : app1
  template:
    metadata:
      name: maven-web-application
      labels:
        name: app1
    spec:
      containers:
      - name: mavenappc
        image: heartocean/k8s:18
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavserv
  namespace: ts
spec:
  type: NodePort
  selector:
    name: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001 
