apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep4
  namespace: ts
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 4
  selector: 
    matchLabels:
      app: mavenapp4
  template:  
    metadata:
      name: pod2-template
      labels:
        app: mavenapp4
    spec:
      containers:
      - name: mavenapp4c
        image: heartocean/k8s:6
        ports:
        - containerPort: 8080
        resources:
          requests: 
            cpu: "200m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "600Mi"
        
---
apiVersion: v1
kind: Service
metadata: 
  name: mav4serv
  namespace: ts
spec:
  type: NodePort
  selector:
    app: mavenapp4
  ports:
  - protocol:  TCP
    port: 80
    targetPort: 8080
    nodePort: 30004
