apiVersion: v1
kind: Pod
metadata: 
  name: a1
  namespace: ts
spec:
  containers: 
    - name: c1
      image: heartocean/docom:1
      ports:
        - name: tomcport
          containerPort: 8080
      volumeMounts:
        - name: hp-1
          mountPath: /tom/tomcat
  volumes:
    - name: hp-1
      hostPath: 
        path: /home/ansible/con2
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: ts
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
