apiVersion: v1
kind: Pod
metadata:
  name: b1
  namespace: ts
spec:
  containers:
    - name: hppod1
      image: heartocean/docom:2
      ports:
        - name: tomp1
          containerPort: 8080
      volumeMounts:
        - name: hp1
          mountPath: /tom/tomcat
  volumes:
    - name: hp1
      hostPath:
        path: /home/debian/hostvol
        type: DirectoryOrCreate 
---
apiVersion: v1
kind: Service
metadata:
  name: a4
  namespace: ts
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: tomp1
          
