apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc1
  namespace: ts
spec:
  #storageClassName: ''
  resources: 
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistencVolumeReclaimPolicy: delete
