apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1dep
  namespace: ts
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: app10
  template:
    metadata:
      labels:
        app: app10
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp
          env:
            - name: MONGODB_ROOT_USERNAME
              value: mongo
            - name: MONGODB_ROOT_PASSWORD
              value: mongopass
            - name: MONGODB_ROOT_HOSTNAME
              value: mongoc
        - name: mongoc
          image: mongo
          ports: 
            - containerPort: 27017
              name: mongocp
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
        volumeMounts:
          - n
---
apiVersion: v1
kind: Service
metadata:
  name: app10serv
  namespace: ts
spec:
  type: NodePort
  selector:
    app: app10
  ports: 
    - targetPort: tomcp
      port: 80
      nodePort: 30000
