apiVersion: v1
kind: PersistentVolume
metadata: 
  name: hp1
  labels:
    app: app10vol
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /space
    type: DirectoryOrCreate
    
