apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec: 
  resources:
    requests:
      storage: 1Gi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: app10
