apiVersion: v1
kind: DaemonSet
metadata:
  name: dameon1
  namespace: ts
spec:
  selector:
    matchLabels:
      app: agents
  template:
    metadata:
      name: agent-temp
      labels:
        app: agents
    spec:
      containers:
      - name: agent1
        image:
        port: 
