apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageserver-efs
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-92107410
  directoryPerms: "700"
