apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sset-efs-aws1
  namespace: ts
spec:
  replicas: 3
  selector: 
    matchLabels:
      appname: sset-efs-aws
  template:
    metadata:
      name: sset-pods
      labels:
        appname: sset-efs-aws
    spec:
      containers: 
        - name: tomc
          image: heartocean/docom:kaniko3
          ports:
            - containerPort: 8080
              name: tomcp
          env:
            - name: MONGO_DB_USERNAME
              value: muser
            - name: MONGO_DB_PASSWORD
              value: mongopass
            - name: MONGO_DB_HOSTNAME
              value: mongoc
                
        - name: mongoc
          image: mongo
          ports: 
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: muser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          volumeMounts:
            - name: sset-efs-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: sset-efs-claim
      spec:
        storageClassName: storageserver-efs
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
