apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volserver-efs1
provisioner: efs.csi.aws.com #ebs.csi.aws.com #nfs.csi.k8s.io
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-92107410
  directoryPerms: "700"
