apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sset-efs1
  namespace: ts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sset-efs
  template:
    metadata:
      name: temp1
      labels:
        app: sset-efs
    spec:
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - name: tomcp
              containerPort: 8080
          env:
            - name: MONGO_DB_USERNAME
              value: muser
            - name: MONGO_DB_PASSWORD
              value: mongopass
            - name: MONGO_DB_HOSTNAME
              value: mongoc
        - name: mongoc
          image: mongo
          ports:
            - name: mongocp
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: muser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          volumeMounts:
            - name: vol1
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: vol1
      spec:
        storageClassName: volserver-efs1
        accessModes: 
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-efs1
  namespace: ts
spec:
  clusterIP: None
  selector: 
    app: sset-efs
  ports:
    - port: 80
      targetPort: tomcp
