apiVersion: v1
kind: Secret
metadata: 
  name: secret1
  namespace: ts
data:
  .password-file: 34342safa53=
---
apiVersion: v1
kind: Pod
metadata:
  name: alpod
  namespace: ts
spec:
  containers:
    - name: alpodc
      image: alpine
      command: ["sleep", "3500"]
      volumeMounts:
        - name: secret-vol
          mountPath: "/etc/secret-vol"
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: secret1 
