image:
  repository: heartocean/cat
  tag: "trial1"

volumes:
  - name: vol1
    secret: 
      secretName: docker-credentials
      items:
        - key: .dockerconfigjson
          path: config.json

volumeMounts: 
  - name: vol1
    mountPath: /home/.docker/
    readonly: true
