apiVersion: v1
kind: LimitRange
metadata:
  name: lr1
spec:
  limits:
    - default: 
        cpu: 200m
      defaultRequest:
        cpu: 200m
      max:
        cpu: 1
      min: 
        cpu 100m
      target: container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdep1
  namespace: ts
spec:
  strategy: 
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: app10
  template:
    metadata:
      labels:
        app: app10
        namespace: ts
    spec:
      nodeSelector:
        name: first
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp
          #livenessProbe
          #resources and limits
          #volumeMounts
