apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-podaffinity
  namespace: ts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app11
  template:
    metadata:
      labels:
        app: app11
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - app10
              topologyKey: nodeName
      containers:
        - name: tomc
          image: heartocean/docom:kj11
          ports:
            - containerPort: 8080
              name: tomcp          
