apiVersion: apps/v1
kind: Deployment
metadata: 
  name: d1
  namespace: ts
spec:
  selector:
    matchLabels:
      name: tomcat
  replicas: 2 
  template:
    metadata: 
      labels:
        name: tomcat
    spec:
      containers:
      - name: tomcat
        image: heartocean/working:tomcat
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: tomcatserv
  namespace: ts
spec:
  type: NodePort
  selector:
    name: tomcat
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
