apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs_1
  namespace: ts
spec:
  replicas: 2  
  selector:
    matchLabels:
      name: tom
  template:
    metadata: 
      name: tomcat
      labels:
        name: tom
    spec:
      containers: 
      - name: tomcatc
        image: heartocean/working:tomcat
        ports: 
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: tomser
  namespace: ts
spec:
  selector:
    name: tom
  ports:
  - port: 80
    targetPort: 8080
