apiVersion: v1
kind: Pod
metadata: 
  name: tompod
  namespace: practise
  labels:
    name: tomcat
spec:
  containers:
  - name: tomcon
    image: heartocean/working:tomcat
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tom-serv
  namespace: practise
spec:
  type: ClusterIP
  selector: 
    name: tomcat
  ports:
  - port: 80
    targetPort: 8080
